"""multi_role_templates_and_requested_role

Revision ID: 0a84d9672b90
Revises: d14cc8eb7a67
Create Date: 2026-06-27 18:19:02.393794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a84d9672b90'
down_revision: Union[str, None] = 'd14cc8eb7a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add requested_role to document_requests (nullable, no backfill needed)
    op.add_column('document_requests', sa.Column('requested_role', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_document_requests_user_id'), table_name='document_requests', if_exists=True)

    # 2. Add roles as nullable first so existing rows don't fail
    op.add_column('document_templates', sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True))

    # 3. Backfill: wrap existing single role value into an array
    op.execute("UPDATE document_templates SET roles = ARRAY[role]")

    # 4. Now that every row has a value, enforce NOT NULL
    op.alter_column('document_templates', 'roles', nullable=False)

    # 5. Drop the old single-role column and its index
    op.drop_index(op.f('ix_document_templates_role'), table_name='document_templates', if_exists=True)
    op.drop_column('document_templates', 'role')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_document_templates_role'), 'document_templates', ['role'], unique=False)
    op.drop_column('document_templates', 'roles')
    op.create_index(op.f('idx_document_requests_user_id'), 'document_requests', ['user_id'], unique=False)
    op.drop_column('document_requests', 'requested_role')
    # ### end Alembic commands ###
