"""learning_paths — self-paced ordered course sequences (2026-08-08)

Backs the student-facing "learning path" surface (design 4a "The ledger"):
`learning_paths` is the curated path record (title/description/hero image/
publish gate, same shape as `courses`); `learning_path_steps` is the ordered
course list, mirroring `program_curriculum`'s (program_id/course_id/position)
shape but keyed for self-paced student use — a student "starts" a path by
bulk self-enrolling in every step's course, rather than ops provisioning it
at cohort-add time.

Hand-written rather than autogenerated: `alembic revision --autogenerate`
picked up a large amount of pre-existing, unrelated model/DB drift across the
rest of the schema (type/index/FK differences on dozens of unrelated tables)
that predates this change and isn't part of it — only the two new tables
below are actually being added here.

Revision ID: 3f4f7d1237e1
Revises: d4f0a25e0043
Create Date: 2026-08-08
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3f4f7d1237e1"
down_revision = "d4f0a25e0043"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "learning_paths",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.String(128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("image_bucket", sa.String(64), nullable=True),
        sa.Column("image_path", sa.String(512), nullable=True),
        sa.Column(
            "created_by", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "learning_path_steps",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "learning_path_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("learning_paths.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "course_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("courses.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.UniqueConstraint("learning_path_id", "course_id", name="uq_learning_path_steps_path_course"),
        sa.UniqueConstraint("learning_path_id", "position", name="uq_learning_path_steps_path_position"),
    )
    op.create_index("ix_learning_path_steps_learning_path_id", "learning_path_steps", ["learning_path_id"])


def downgrade() -> None:
    op.drop_index("ix_learning_path_steps_learning_path_id", table_name="learning_path_steps")
    op.drop_table("learning_path_steps")
    op.drop_table("learning_paths")
