"""add_document_templates_table

Revision ID: 719891467635
Revises: 0003
Create Date: 2026-06-27 17:21:53.277648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '719891467635'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('template_file_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_key'), 'document_templates', ['key'], unique=True)
    op.create_index(op.f('ix_document_templates_role'), 'document_templates', ['role'], unique=False)
    op.drop_index(op.f('idx_ambassador_tasks_assigned'), table_name='ambassador_tasks')
    op.alter_column('application_questions', 'options',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_application_questions_deleted'), table_name='application_questions')
    op.drop_index(op.f('idx_document_requests_user_id'), table_name='document_requests')
    op.create_index(op.f('ix_document_requests_user_id'), 'document_requests', ['user_id'], unique=False)
    op.drop_constraint(op.f('epics_created_by_fkey'), 'epics', type_='foreignkey')
    op.create_foreign_key(None, 'epics', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('id_cards', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('id_cards', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_lead_comments_lead'), table_name='lead_comments')
    op.drop_index(op.f('idx_leads_ambassador'), table_name='leads')
    op.drop_constraint(op.f('modules_created_by_fkey'), 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_points_ambassador'), table_name='points_transactions')
    op.drop_constraint(op.f('proposals_proposed_by_fkey'), 'proposals', type_='foreignkey')
    op.drop_constraint(op.f('proposals_reviewed_by_fkey'), 'proposals', type_='foreignkey')
    op.create_foreign_key(None, 'proposals', 'users', ['proposed_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'proposals', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.alter_column('recommendation_letters', 'generated_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('recommendation_letters_generated_by_fkey'), 'recommendation_letters', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation_letters', 'users', ['generated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('task_assignees_user_id_fkey'), 'task_assignees', type_='foreignkey')
    op.create_foreign_key(None, 'task_assignees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_mind_map_notes_updated_by_fkey'), 'task_mind_map_notes', type_='foreignkey')
    op.create_foreign_key(None, 'task_mind_map_notes', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('task_submissions_submitted_by_fkey'), 'task_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'task_submissions', 'users', ['submitted_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_teacher_applications_invited_by'), table_name='teacher_applications')
    op.drop_index(op.f('idx_teacher_applications_status'), table_name='teacher_applications')
    op.drop_index(op.f('idx_sessions_teacher'), table_name='teacher_sessions')
    op.drop_constraint(op.f('team_members_user_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('uq_users_invite_code'), table_name='users')
    op.create_unique_constraint(None, 'users', ['invite_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('uq_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_user_id_fkey'), 'team_members', 'users', ['user_id'], ['id'])
    op.create_index(op.f('idx_sessions_teacher'), 'teacher_sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_teacher_applications_status'), 'teacher_applications', ['status'], unique=False)
    op.create_index(op.f('idx_teacher_applications_invited_by'), 'teacher_applications', ['invited_by_id'], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'task_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('task_submissions_submitted_by_fkey'), 'task_submissions', 'users', ['submitted_by'], ['id'])
    op.drop_constraint(None, 'task_mind_map_notes', type_='foreignkey')
    op.create_foreign_key(op.f('task_mind_map_notes_updated_by_fkey'), 'task_mind_map_notes', 'users', ['updated_by'], ['id'])
    op.drop_constraint(None, 'task_assignees', type_='foreignkey')
    op.create_foreign_key(op.f('task_assignees_user_id_fkey'), 'task_assignees', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recommendation_letters', type_='foreignkey')
    op.create_foreign_key(op.f('recommendation_letters_generated_by_fkey'), 'recommendation_letters', 'users', ['generated_by'], ['id'])
    op.alter_column('recommendation_letters', 'generated_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.create_foreign_key(op.f('proposals_reviewed_by_fkey'), 'proposals', 'users', ['reviewed_by'], ['id'])
    op.create_foreign_key(op.f('proposals_proposed_by_fkey'), 'proposals', 'users', ['proposed_by'], ['id'])
    op.create_index(op.f('idx_points_ambassador'), 'points_transactions', ['ambassador_id'], unique=False)
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key(op.f('modules_created_by_fkey'), 'modules', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_leads_ambassador'), 'leads', ['ambassador_id'], unique=False)
    op.create_index(op.f('idx_lead_comments_lead'), 'lead_comments', ['lead_id'], unique=False)
    op.alter_column('id_cards', 'linkedin_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('id_cards', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'epics', type_='foreignkey')
    op.create_foreign_key(op.f('epics_created_by_fkey'), 'epics', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_document_requests_user_id'), table_name='document_requests')
    op.create_index(op.f('idx_document_requests_user_id'), 'document_requests', ['user_id'], unique=False)
    op.create_index(op.f('idx_application_questions_deleted'), 'application_questions', ['deleted_at'], unique=False)
    op.alter_column('application_questions', 'options',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_index(op.f('idx_ambassador_tasks_assigned'), 'ambassador_tasks', ['assigned_to'], unique=False)
    op.drop_index(op.f('ix_document_templates_role'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_key'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
