"""Index users.contact_id (B4, LMS Phase 2 Stage 0, 2026-08-10).

Every LMS lookup by contact_id (ops_integration.get_or_create_student_account,
instructor_progress.session_lms_progress — one per roster row) was a
sequential scan; contact_id has no index at all today. Standalone index, not
a UNIQUE constraint — contact_id can still hold duplicates until Phase 2
Stage 1's D1 migration reconciles them. That migration adds a UNIQUE
constraint, which Postgres backs with its own index, making this one
redundant — drop it then.

Hand-written, not autogenerated: this schema's autogenerate diff carries a
lot of unrelated drift noise (naming-convention differences, TEXT vs String
type mismatches) left over from the SQL-first baseline (LMS_EXECUTION_PLAN.md
§0.2) that has nothing to do with this change.
"""

from alembic import op

revision = "7d448f6873a9"
down_revision = "a3f7c91d0037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # IF NOT EXISTS: this exact index was found already present on the local
    # dev DB (untracked by Alembic — likely a prior ad-hoc debugging step
    # against B4's sequential-scan symptom). Idempotent either way.
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_contact_id ON users (contact_id)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_users_contact_id")
