"""baseline — full production schema as of Alembic adoption (2026-07-10)

Revision ID: baseline
Revises:
Create Date: 2026-07-10

This is the single baseline revision created when the project adopted Alembic.
Before this, the schema was built "SQL-first" (numbered backend/sql/*.sql files
+ idempotent startup DDL in main.py) — Alembic autogenerate could not faithfully
reproduce that (raw enums with create_type=False, sequences, partial indexes,
server defaults, etc.), so the baseline is a verbatim `pg_dump --schema-only` of
the live production database, lightly cleaned (psql \restrict meta-commands, the
search_path reset, and the superuser-only COMMENT ON EXTENSION removed).

- On EXISTING databases (production, dev) this revision is applied via
  `alembic stamp baseline` — recorded as done WITHOUT running (they already have
  the schema).
- On a FRESH empty database, `alembic upgrade head` runs baseline_schema.sql to
  build the whole schema. Prerequisite: the `pgcrypto` extension must be
  creatable (the tables' gen_random_uuid() defaults need it) — create the DB and
  extension as a superuser first, exactly as the provisioning step already does.

Every schema change AFTER this point is a normal, autogenerated-and-reviewed
Alembic revision that runs exactly once. main.py's startup DDL is retired.
"""

from pathlib import Path

from alembic import op

# revision identifiers, used by Alembic.
revision = "baseline"
down_revision = None
branch_labels = None
depends_on = None

_SCHEMA_SQL = Path(__file__).parent / "baseline_schema.sql"


def upgrade() -> None:
    sql = _SCHEMA_SQL.read_text(encoding="utf-8")
    # exec_driver_sql → psycopg2 cursor.execute, which runs the multi-statement
    # dump in one shot (SQLAlchemy text() would try to parse/parametrize it).
    op.get_bind().exec_driver_sql(sql)


def downgrade() -> None:
    # Downgrading below the baseline would drop the entire application schema —
    # deliberately not automated. Do it by hand if you genuinely mean to.
    raise NotImplementedError(
        "The baseline revision cannot be downgraded (it would drop the whole schema)."
    )
