"""increase_role_length_in_templates

Revision ID: d14cc8eb7a67
Revises: 719891467635
Create Date: 2026-06-27 18:11:26.530859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14cc8eb7a67'
down_revision: Union[str, None] = '719891467635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_requests_user_id'), table_name='document_requests')
    op.alter_column('document_templates', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_templates', 'role',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_document_requests_user_id'), 'document_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###
