"""inventory schema — locations, items, kit templates, kits, stock, movements (I1-1)

Eight tables, one CHECK constraint, no state machines, no circular FKs.

Hand-written rather than autogenerated on purpose: `baseline_schema.sql` has
known pre-existing drift from the models (TEXT vs String on many older
columns, idx_ vs ix_ index naming), so `--autogenerate` emits that noise on
every diff. Folding it into an unrelated revision is explicitly warned against
in MASTER_EXECUTION_PLAN_V2.md §DISCOVERIES.

Nothing here references `contacts`, so MERGE_FK_REGISTRY is untouched by
design — custody keys on `users`.

Revision ID: d5a1c73f0016
Revises: c4f9b25e0015
Create Date: 2026-07-28
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d5a1c73f0016"
down_revision = "c4f9b25e0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "locations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("country", sa.String(2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(128), nullable=False, unique=True),
        sa.Column("category", sa.String(32), nullable=False, server_default="other"),
        sa.Column("is_consumable", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("returnable_default", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "kit_templates",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(64), nullable=False),
        sa.Column("code", sa.String(16), nullable=False, unique=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "kit_template_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "template_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("kit_templates.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "item_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("items.id", ondelete="RESTRICT"), nullable=False,
        ),
        sa.Column("required_qty", sa.Integer(), nullable=False, server_default="1"),
        sa.UniqueConstraint("template_id", "item_id", name="uq_kit_template_item"),
    )

    op.create_table(
        "kits",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "template_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("kit_templates.id", ondelete="RESTRICT"), nullable=False,
        ),
        sa.Column("label", sa.String(32), nullable=False, unique=True),
        sa.Column("public_token", sa.String(64), nullable=False, unique=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="working"),
        sa.Column(
            "current_location_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("locations.id", ondelete="RESTRICT"), nullable=False,
        ),
        # SET NULL, never CASCADE — a departing staff member must not erase the
        # custody history of the kit they were holding.
        sa.Column(
            "current_holder_user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_kits_current_location_id", "kits", ["current_location_id"])
    op.create_index("ix_kits_current_holder_user_id", "kits", ["current_holder_user_id"])

    op.create_table(
        "kit_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "kit_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("kits.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "item_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("items.id", ondelete="RESTRICT"), nullable=False,
        ),
        sa.Column("qty", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("kit_id", "item_id", name="uq_kit_item"),
    )

    op.create_table(
        "stock_levels",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "item_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("items.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "location_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("locations.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("qty", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("item_id", "location_id", name="uq_stock_item_location"),
    )

    op.create_table(
        "movements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "kit_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("kits.id", ondelete="CASCADE"), nullable=True,
        ),
        sa.Column(
            "item_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("items.id", ondelete="RESTRICT"), nullable=True,
        ),
        sa.Column("qty", sa.Integer(), nullable=True),
        sa.Column(
            "from_location_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("locations.id", ondelete="RESTRICT"), nullable=True,
        ),
        sa.Column(
            "from_user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "to_location_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("locations.id", ondelete="RESTRICT"), nullable=True,
        ),
        sa.Column(
            "to_user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "session_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("reason", sa.String(32), nullable=False),
        sa.Column("due_back_on", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_by", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column(
            "confirmed_by", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(kit_id IS NOT NULL) <> (item_id IS NOT NULL)",
            name="ck_movement_kit_xor_item",
        ),
    )
    op.create_index("ix_movements_kit_id", "movements", ["kit_id"])
    op.create_index("ix_movements_item_id", "movements", ["item_id"])
    op.create_index("ix_movements_session_id", "movements", ["session_id"])
    # The overdue query: due_back_on in the past with no return recorded.
    op.create_index("ix_movements_due_back_on", "movements", ["due_back_on"])


def downgrade() -> None:
    # Safe to run in principle (these tables are new and referenced by
    # nothing), but see HANDOFF_V2_LIVE.md: downgrading is not the rollback
    # path on this deployment — roll back the image and leave the schema.
    op.drop_table("movements")
    op.drop_table("stock_levels")
    op.drop_table("kit_items")
    op.drop_table("kits")
    op.drop_table("kit_template_items")
    op.drop_table("kit_templates")
    op.drop_table("items")
    op.drop_table("locations")
