"""lms schema — courses, modules, items, videos, curriculum, enrollments, progress (LM1-1)

Seven tables, no CHECK constraints, no state machines, no circular FKs. This
is the §2 schema of LMS_EXECUTION_PLAN.md, one revision, on head
c7e2b41a0039 (the LM0-2 student-role migration).

Authored content (text bodies, quiz questions/options, flashcard cards)
collapses into `module_items.content` JSONB instead of six normalized tables —
it is authored and read as a whole unit, never filtered, joined or aggregated.
`module_videos` keeps real columns because it holds async state the transcode
worker writes. `enrollments` and `item_progress` CASCADE on user delete on
purpose: a deleted student's progress is worthless without the student (the
inverse of inventory custody, which preserves history).

Hand-written rather than autogenerated on purpose, same as d5a1c73f0016:
`baseline_schema.sql` has known pre-existing drift from the models, so
`--autogenerate` emits that noise on every diff.

Nothing here references `contacts` — enrollments key on `users`, so
MERGE_FK_REGISTRY is untouched by design.

Revision ID: e2f7a93d0040
Revises: c7e2b41a0039
Create Date: 2026-08-04
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e2f7a93d0040"
down_revision = "c7e2b41a0039"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "courses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("title", sa.String(128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        # course|mission (mission = Phase 2)
        sa.Column("kind", sa.String(12), nullable=False, server_default="course"),
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_by", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "course_modules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "course_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("courses.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("title", sa.String(128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.UniqueConstraint("course_id", "position", name="uq_course_modules_course_position"),
    )

    op.create_table(
        "module_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "module_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("course_modules.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        # video|text|quiz|flashcards
        sa.Column("kind", sa.String(10), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("title", sa.String(128), nullable=True),
        # Authored payload; shapes in LMS_EXECUTION_PLAN.md §2. No DB-level
        # guard against answer leakage — that lives in student_view() (LM1-2).
        sa.Column("content", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.UniqueConstraint("module_id", "position", name="uq_module_items_module_position"),
    )

    op.create_table(
        "module_videos",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "item_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("module_items.id", ondelete="CASCADE"),
            nullable=False, unique=True,
        ),
        # Original MP4, never served to students.
        sa.Column("source_bucket", sa.String(64), nullable=False),
        sa.Column("source_path", sa.String(512), nullable=False),
        # HLS playlist + AES-128 key once transcoded (D2 — key is a file via
        # the storage facade, so Fernet-at-rest comes free).
        sa.Column("playlist_path", sa.String(512), nullable=True),
        sa.Column("key_path", sa.String(512), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        # pending|processing|ready|failed
        sa.Column("transcode_status", sa.String(12), nullable=False, server_default="pending"),
        sa.Column("transcode_error", sa.Text(), nullable=True),
    )

    op.create_table(
        "program_curriculum",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "program_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("programs.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "course_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("courses.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.UniqueConstraint("program_id", "course_id", name="uq_program_curriculum_program_course"),
        sa.UniqueConstraint("program_id", "position", name="uq_program_curriculum_program_position"),
    )

    op.create_table(
        "enrollments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "course_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("courses.id", ondelete="CASCADE"), nullable=False,
        ),
        # self|ops|registration
        sa.Column("source", sa.String(12), nullable=False, server_default="self"),
        # Provenance only — how this enrollment STARTED, never live membership
        # (§2 note; UNIQUE(user_id, course_id) records only the first path in).
        sa.Column(
            "program_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("programs.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "registration_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("registrations.id", ondelete="SET NULL"), nullable=True,
        ),
        # active|inactive
        sa.Column("status", sa.String(10), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollments_user_course"),
    )

    op.create_table(
        "item_progress",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "item_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("module_items.id", ondelete="CASCADE"), nullable=False,
        ),
        # not_started|in_progress|completed|skipped
        sa.Column("status", sa.String(12), nullable=False, server_default="not_started"),
        sa.Column("quiz_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("best_score", sa.Numeric(5, 2), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("user_id", "item_id", name="uq_item_progress_user_item"),
    )


def downgrade() -> None:
    # Safe to run in principle (these tables are new and referenced by
    # nothing), but see HANDOFF_V2_LIVE.md: downgrading is not the rollback
    # path on this deployment — roll back the image and leave the schema.
    op.drop_table("item_progress")
    op.drop_table("enrollments")
    op.drop_table("program_curriculum")
    op.drop_table("module_videos")
    op.drop_table("module_items")
    op.drop_table("course_modules")
    op.drop_table("courses")
